# Generated by Django 2.2.4 on 2019-08-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20190803_0403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desccription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='shop/images/products'),
        ),
    ]
